replicaCount: 2

secretName: cdc-consumer-ui-secrets

container:
  name: cdc-consumer-ui

image:
  repository: host.minikube.internal:8082/cdc-consumer-ui
  tag: "3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

imagePullSecrets:
  - name: nexus-registry

aws:
  region: us-east-1

postgres:
  host: postgres
  port: 5432

env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: "my-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"

  - name: KAFKA_TOPIC
    value: "postgres.public.requests"