replicaCount: 3

nameOverride: ""

secretName: distributed-web-app-secrets

container:
  name: distributed-web-app

image:
  repository: host.minikube.internal:8082/distributed-web-app
  tag: "50"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

imagePullSecrets:
  - name: nexus-registry

aws:
  region: us-east-1

postgres:
  host: postgres
  port: 5432