apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: second-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/HaikGr/distributed-web-app-deployment.git
    targetRevision: HEAD
    path: helm/distributed-web-app
    helm:
      valueFiles:
        - values-app2.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true