replicaCount: 1

image:
  repository: postgres
  tag: "17-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432
  targetPort: 5432

persistence:
  size: 1Gi
  accessMode: ReadWriteOnce

postgres:
  database: distributed
  username: Haik_Gr
  password: Hayko200301

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi